### PR TITLE
filtering non-audio tracks for AVAssetReaderTrackOutput

### PR DESCRIPTION
**Pull request by avyavya**
I thought wanna use this framework for mp4 video file.

AVAssetReaderTrackOutput raises NSInvalidArgumentException when analyze non-audio tracks with the outputSettings().
this fix will able to supports for movie files (.mp4 and more)

sorry for no tests...

### CODE REVIEW

**Comment by dmrschmidt** [comment]
Hey avyavya, thanks for the PR! Just took a quick look from my phone and it looks good. I’ll merge and release it today or tomorrow when I’m back at my laptop.

Thanks a lot!

**Comment by dmrschmidt** [comment]
I'll merge this now since it looks right, works for me and I can't see any potential issues. However, with the videos I just tried it with, I actually never got the crash you mentioned. So either there is still some other issue at play, or it's simply the way the videos are encoded and presumably their tracks arranged or something.

@avyavya, would it be possible to send me the video file that caused the `NSInvalidArgumentException` to me?

**Comment by avyavya** [comment]
Hi @dmrschmidt ! thanks for merge :)

I tested with video downloaded from https://mazwai.com/video/excuse-the-roach-iii---miami/454986

`NSInvalidArgumentException` occures when `audioAsset.tracks.first.mediaType` is NOT `AVMediaType.audio`
'the first track' of that video is `AVMediaType.video`

regards 🙇

**Comment by dmrschmidt** [comment]
Thanks for the video! I've tested it now and just as I expected, the issue isn't yet fixed completely.
It doesn't crash any more and reads the file while producing a waveform image, but that image is still wrong.

This is what it looks like
Screen Shot 2020-01-23 at 09 31 25

and this is what it should look like
Screen Shot 2020-01-23 at 09 32 42

So it's only loading like a quarter or whatever of the actual audio data in this example.

I've isolated the issue to the way audio data is encoded in the tracks of a video. Looks like I'll need to rewrite the whole loading process of the `AVAssetReader` to get the proper values for the duration.

Working on that now.

**Comment by dmrschmidt** [comment]
This is now fixed properly and released as `6.0.0`.

As the semantic versioning indicates, this is an API breaking change as the workflow is now always asynchronous.

**Comment by avyavya** [comment]
thx for update! ☺️

btw, tag `6.1.0` does not exists for me 🤔
commit: https://github.com/dmrschmidt/DSWaveformImage/commit/d16f193f0e47ed950c9e1602e55295b73c9969d2 is gone?

**Comment by dmrschmidt** [comment]
🤔 Guess i forgot something. Will check tomorrow. I tried it on one of my
own projects with Carthage and it updated to 6.1.0 but I’ll see what’s
missing. Thanks for letting me know!

**Comment by dmrschmidt** [comment]
> thx for update! ☺️
> 
> btw, tag `6.1.0` does not exists for me 🤔
> commit: [d16f193](https://github.com/dmrschmidt/DSWaveformImage/commit/d16f193f0e47ed950c9e1602e55295b73c9969d2) is gone?

I had indeed forgotten to push the actual commit and not just the tag 🤦‍♂️
all there now

**Pull request merged**
